apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-final
  name: backend-service
spec:
  selector:
    app: fast-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-final
  name: backend
  labels:
    app: fast-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-backend
  template:
    metadata:
      labels:
        app: fast-backend
    spec:
      containers:
        - name: backend-fast
          image: ghcr.io/sergiomdza/desarrollo_web_3_longitudinal:{imagen}-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
