FROM python:3.12-slim

WORKDIR /app

COPY . .

EXPOSE 8000

RUN pip install --no-cache-dir "poetry"

RUN poetry install --no-root --only main --no-cache

CMD ["poetry", "run", "fastapi", "dev", "main.py", "--host", "0.0.0.0"]
