FROM python:3.12-slim

WORKDIR /app

COPY . .

EXPOSE 8000

RUN pip install --no-cache-dir "poetry"

RUN pip install poetry \
&& poetry config virtualenvs.create false \
&& poetry install --no-root --no-interaction

CMD ["poetry", "run", "fastapi", "dev", "app/main.py", "--host", "0.0.0.0"]
