apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: proyecto-final
data:
  MONGO_HOST: mongo-service
  MONGO_PORT: "27017"
  MONGO_DB: notifications_db
  MONGO_AUTH_SOURCE: admin