apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-requests
  namespace: proyecto-final

  labels:
    app: backend-requests

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend-requests

  template:
    metadata:
      labels:
        app: backend-requests

    spec:
      containers:

        - name: backend-requests

          image: ghcr.io/sergiomdza/desarrollo_web_3_longitudinal-requests:equipo_4-latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: backend-config

          env:

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 20
            periodSeconds: 10

---

apiVersion: v1
kind: Service

metadata:
  name: backend-requests-service
  namespace: proyecto-final

spec:
  selector:
    app: backend-requests

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP