apiVersion: v1
kind: Secret

metadata:
  name: mongo-secret
  namespace: proyecto-final

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: web3

  MONGO_URI: mongodb://admin:web3@mongo-service.proyecto-final.svc.cluster.local:27017/?authSource=admin