[project]
name = "audits"
version = "0.1.0"
description = ""
authors = [
    {name = "Eliam28",email = "152578969+Eliam28@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymongo (>=4.18.2,<5.0.0)",
    "fastapi (>=0.142.0,<0.143.0)",
    "uvicorn (>=0.54.0,<0.55.0)",
    "prometheus-fastapi-instrumentator (>=8.1.0,<9.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
