name: Backend - Users

on:
  push:
    branches:
      - CI-CD

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  first_try:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Print Image name
        run: echo "$IMAGE_NAME"
